# Generated by Django 2.1.2 on 2019-05-16 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.CharField(max_length=120, verbose_name='access token')),
                ('refresh_token', models.CharField(max_length=120, verbose_name='refresh token')),
                ('realm_id', models.CharField(max_length=60, verbose_name='realm_id')),
            ],
        ),
    ]
